/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <gpio.h>
#include <rcc.h>

int main(void)
{
	gpio_init();
	gpio_set_outdata(GPIOG_BASE, GPIO_PIN_13, 1);
	gpio_set_outdata(GPIOG_BASE, GPIO_PIN_14, 1);

    while (1)
    {
    }
}
