/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <mem_io.h>
#include <gpio.h>
#include <rcc.h>
#include <usart.h>
#include <exti.h>
#include <ltdc.h>
#include <fmc.h>

void delay_us(uint32_t us) {
    for (volatile uint32_t i = 0; i < us * 168 / 4; ++i) {}
}

int main(void)
{
	gpio_init();
	usart_init();
	exti_init();

	gpio_set_outdata(GPIOG_BASE, GPIO_PIN_13, 1);
	gpio_set_outdata(GPIOG_BASE, GPIO_PIN_14, 1);

	usart_print(USART1_BASE, "USART\r\n");
	usart_write(USART1_BASE, 't');
	usart_write(USART1_BASE, 'e');
	usart_write(USART1_BASE, 'x');
	usart_write(USART1_BASE, 't');
	usart_write(USART1_BASE, '\r');
	usart_write(USART1_BASE, '\n');

	ltdc_gpio_init();

	// fmc_init();
	// sdram_self_test();

    while (1)
    {
    	usart_printf("enter while \r\n");
    	delay_us(100);
    	//for (volatile int i = 0; i < 1000000; i++); // about 1 second

    }
}
